export const dataDescriptions: Record<string, string> = {
    'Network Status': 'Indicates if your browser is currently connected to the internet. "Enabled" means you are online.',
    'Connection Type': 'Estimates the effective type of the connection the user\'s device is using to communicate with the network (e.g., 4G, Wi-Fi). This is an approximation.',
    'IP Address': 'Your public Internet Protocol (IP) address. This is the address websites use to send data to your device over the internet.',
    'ISP': 'Your Internet Service Provider (ISP) is the company that provides you with internet access.',
    'City': 'The estimated city associated with your current IP address.',
    'Country': 'The estimated country associated with your current IP address.',
    'User Agent': 'A string of text that your browser sends to websites to identify itself. It includes details like browser name, version, and your operating system.',
    'Platform': 'The platform on which the browser is running (e.g., Win32, Linux x86_64, MacIntel).',
    'Language': 'The preferred language of the user, usually the language of the browser UI.',
    'Browser Vendor': 'The vendor of the browser (e.g., Google Inc., Mozilla).',
    'Do Not Track': 'Indicates the user\'s tracking preference. "1" means the user has requested not to be tracked.',
    'Cookies Enabled': 'Indicates whether cookies are enabled in the browser. Cookies are small pieces of data websites store on your device.',
    'PDF Viewer Enabled': 'Indicates if the browser has a built-in PDF viewer.',
    'Touch Support': 'Indicates if the device supports touch events.',
    'Screen Width': 'The total width of the user\'s screen in pixels.',
    'Screen Height': 'The total height of the user\'s screen in pixels.',
    'Available Screen Width': 'The width of the screen available for windows, excluding interface features like the OS taskbar.',
    'Available Screen Height': 'The height of the screen available for windows, excluding interface features like the OS taskbar.',
    'Window Width': 'The width of the browser window\'s viewport in pixels.',
    'Window Height': 'The height of the browser window\'s viewport in pixels.',
    'Screen Orientation': 'The current orientation of the screen (e.g., landscape-primary, portrait-primary).',
    'Color Depth': 'The number of bits used to represent the color of a single pixel in a screen.',
    'Pixel Depth': 'The number of bits used to represent the color of a single pixel. It is similar to Color Depth but may include an alpha channel.',
    'Device Pixel Ratio': 'The ratio of physical pixels to logical pixels (CSS pixels). A value > 1 indicates a high-resolution (Retina) display.',
    'Device Memory (GB)': 'An estimate of the amount of RAM on the device in gigabytes.',
    'CPU Cores': 'The number of logical processor cores available to run threads on the user\'s computer.',
    'Timezone': 'The timezone of the user\'s system as reported by the browser.',
    'Geolocation Permission': 'The status of the permission for the website to access your device\'s location (e.g., granted, prompt, denied).',
    'Battery Level': 'The current battery level of the device as a percentage.',
    'Charging Status': 'Indicates if the device\'s battery is currently charging.',
    'Operating System': 'The operating system your device is running, as identified from the browser\'s User Agent string.',
    'Device Model': 'The model of your device, as identified from the browser\'s User Agent string. This is often more accurate on mobile devices.',
    'Network Speed (Mbps)': 'An estimate of the download speed in Megabits per second (Mbps) for your current connection. This is based on the connection type and conditions.',
    'Round-Trip Time (ms)': 'An estimate of the round-trip time in milliseconds (ms). This is the time it takes for a signal to get from your device to a server and back, indicating network latency.',
    'Data Saver': 'Indicates if you have enabled the data-saving feature in your browser, which may reduce data usage by compressing images and other content.',
};